language: ruby
script: bundle exec rspec spec
before_script:
- psql -c 'create database shop_one_test_db;' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: SqvMonMNUwhBDYOnOzEBxAwUT4hPORKSyyxGyEwLNu0Tr9gEPoJenIBVFyXqFAGyIuZ2cFdMQsxAUWTwiymKAXAEUHVufU8FbFykkxI5hPJF72xYtzGVTI3IunNjL+SWrzETAakX3KUoA9johc4G3bxMkq1WWVxbxyIKNUpMeTOMDd1CUxFkpt+5czYO/OEwY7YasPztnOV34KpsUROe7Gct3FUsFv4sSRkBOHtj3yEoh3j1dghz/WfY+eiTLUaEU0I9a3mM+EA/+qhlBARwwrWr6HHLFl5TvdXKEqyZB06EPfzcL20tK4RPBH9tSq9pSZrATWLPLNoqbk5CSK2s8TiodRsJCgdECdulWKdtLWkiL4xAkWuLpNZvhnD4L5EuIpRUSCtt1McIpUxe6Tm97RSRSkXgkxfWXqvohFSkIC0lGSb6ReTDk//zpQaJVsfiKOMGUnQqeyLDLcVYNsae9MtRJkw/2qV0L6jd4sl6PVHC4RXz8ui6QAZ+07RiMYwzE5lNIIA09yzx/Uepz1KOa3dSm6ASN7iKGugiZKIk8+UcW7CCRSK5FR7dN4FULAke5X4Lo4+84tjsYkNeEtwMpgLfL4+ICjaOSo505pB4YZICqykazqtIHwwigiEzXn3N4QzhY4VHd9aKR85rKVJbPfPlpp57Sext8R9z4EMRwhQ=
  app: rocky-river-5952
  on: master